name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'BeatSaberPlaylistsLib/**'
      - '.github/workflows/BuildMaster.yml'
  pull_request:
    branches: [ master ]
    paths: 'BeatSaberPlaylistsLib/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build Lib
      id: Build-Lib
      run: dotnet build --configuration Release
    - name: GetStrippedRefs
      env:
        FILES_URL: ${{ secrets.BSFILES_URL }}
      run: wget --no-check-certificate "$FILES_URL" -q -O bsfiles.zip
    - name: ExtractRefs
      run: unzip -q -n bsfiles.zip -d ./Refs
    - name: Build For Beat Saber
      id: Build-BeatSaber
      run: dotnet build --configuration Release-BeatSaber
    - name: Upload Lib Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build-Lib.outputs.filename }}
        path: ${{ steps.Build-Lib.outputs.artifactpath }}
    - name: Upload Beat Saber Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build-BeatSaber.outputs.filename }}
        path: ${{ steps.Build-BeatSaber.outputs.artifactpath }}
